### ISSUE TITLE
jump to queue item

### ISSUE THREAD

**Issue by eprst** [rbackhouse/mpdjs#11]
One more feature request: there must be a way to jump to a specific queue item, probably by (double?) tapping on it.
Thanks!

**Comment by rbackhouse** [comment]
I can have it work that when the queue is not it edit mode it will play the song tapped

**Comment by eprst** [comment]
yes, that's what i mean

On Mar 11, 2018 06:02, "Richard Backhouse" <notifications@github.com> wrote:

I can have it work that when the queue is not it edit mode it will play the
song tapped

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rbackhouse/mpdjs/issues/11#issuecomment-372113797>, or mute
the thread

**Comment by rbackhouse** [comment]
Version 3.0 is now available in the App store with this functionality

**Comment by eprst** [comment]
thank you!
