### ISSUE TITLE
Unable to list artists, albums, or song search

### ISSUE THREAD

**Issue by asktoby** [rbackhouse/mpdjs#4]
Hello,
Bought the ios app, v1.1.
Playlist functions are working fine.
Clicking Artists, Albums or Song Search results in an infinite spinning progress indicator.
Let me know if there is more information I can provide.
Thanks
Toby

**Comment by rbackhouse** [comment]
It would help if you could get me a list of the artists and albums in your database. Can you use the mpc tool and run

mpc list artist
mpc list album

and send me the lists.

Thanks

**Comment by asktoby** [comment]
Just emailed you the lists.

**Comment by rbackhouse** [comment]
Thanks for the lists

I'm not seeing any problems loading the artists or albums from them though. 
I had suspected that there might have been problems with some of the characters in the tags but that does not seem to be the case.

If you can it would help if you run the app while connected to a Safari instance to get a a Web Inspector session, I'm hoping that the console output will help trying to figure out whats going wrong.

There are some tips on doing this here : http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html

Additional, can you give a little more detail on what you are running. i.e iOS version and device type. Also the version of MPD you are connecting to.

Thanks

**Comment by asktoby** [comment]
iOS version 8.4 (12H143)
Device type Iphone 5c
MPD Version: 0.18.0 running on Ubuntu server.

I don't have any Apple computers so I don't think I can connect to a Safari Instance: "*With Safari 6 and higher (OS X only, sorry Windows) you can use Safari’s developer tools to remotely debug web pages in mobile Safari on an iOS device.*"

**Comment by rbackhouse** [comment]
Would it be possible for you to connect to another database, even if its on the same server. It would help to know if this was a general problem you are seeing or just with this particular database you have.

**Comment by asktoby** [comment]
Not easy to set up another database - unless yours is publicly accessible?
I've since noticed that it's an intermittent issue. Once it works once it seems to work every time!

**Comment by rbackhouse** [comment]
Sorry, I don't have a database that you could try. 

Saying it is intermittent though suggests that it is not a database problem. 

I just released version 1.3 to the app store that contains some code that attempts to improve on reporting communication failures. I suspect that that is what you are seeing. I would hope that instead of seeing the spinner you would now get a dialog with some failure information now.

**Comment by asktoby** [comment]
Here is it happening on 1.3:
https://youtu.be/b3zLKl5fQM0

**Comment by rbackhouse** [comment]
Is it always after entering something in the search textbox ?

**Comment by rbackhouse** [comment]
I can now recreate. Will fix for next release

**Comment by rbackhouse** [comment]
Fixed in Version 1.4 now on iTunes
