### ISSUE TITLE
App launches onto "Connected to 192.168..." dialog

### ISSUE THREAD

**Issue by asktoby** [rbackhouse/mpdjs#5]
Hope this is an OK place for a tweak suggestion. :)

The app launches onto "Connected to 192.168..." dialog.
This doesn't seem like a helpful place to start!
Better to launch straight to the playlist?

**Comment by rbackhouse** [comment]
My preference is to launch on the Connections page as I have multiple databases that I connect to. 
I do think though that enabling the selection of the launch page as a configuration option would be of value.

**Comment by rbackhouse** [comment]
Fixed in Version 1.4 now on iTunes

**Comment by asktoby** [comment]
Fantastic, thank you.
