### ISSUE TITLE
Menu button is too small

### ISSUE THREAD

**Issue by asktoby** [rbackhouse/mpdjs#6]
The menu button is too small and often takes many attempts to depress:
http://youtu.be/_0dmDpc6rpA

**Comment by rbackhouse** [comment]
Link returns  "This video is private."

**Comment by asktoby** [comment]
Apologies, fixed now!

**Comment by rbackhouse** [comment]
Fixed in Version 1.4 now on iTunes

**Comment by asktoby** [comment]
Fantastic, thank you
