### ISSUE TITLE
App v1.4 fails to launch 

### ISSUE THREAD

**Issue by asktoby** [rbackhouse/mpdjs#7]
Launching 1.4 yields the below error:

Error: TypeError: undefined is not an object (evaluating 't.getConnection().host') Script: file:///private/var/mobile/Containers/Bundle/Application/92C83AAC-7A55-45D9-9725-65A0FC47CF59/MPD%20js.app/www/js/app-built.js Line: 240 Column: 25964 StackTrace: undefined 

Interestingly, 1.4 worked fine when I tried it while off my LAN earlier today, away from access to my MPD server.
The bug only appeared when I got home to try it out "properly".
Disabling wifi doesn't help.

Video:
https://youtu.be/_RWnqsp6TFc

**Comment by rbackhouse** [comment]
Can you provide any details on what you did when it was off your LAN. 

1) How many connections your had configured, 
2) Did you play with configuring a start page. 

and anything else that you can think of.

If you can't get past this error then you can remove the app from your device to clean its config and reload to start from scratch

**Comment by asktoby** [comment]
1) I did have one connection pre-configured from the previous version.
2) As I recall, yes, I played with configuring the start page but, because I was off the LAN, it didn't pan out well because going to the playlist page didn't make sense.
Removing and re-installing the app fixed the issue.

I've since managed to reproduce it repeatably following the below steps:

0) Connect to LAN
1) Fresh install of MPDjs
2) Open MPDjs
3) Add server [OK]
4) tap "tick" next to newly added server
5) See error: "Error: TypeError: undefined is not an object (evaluating 't.getConnection().host') Script: file:///private/var/mobile/Containers/Bundle/Application/A7A7E5D0-CB75-49E0-B6DB-8B4278F5263E/MPD%20js.app/www/js/app-built.js Line: 240 Column: 25964 StackTrace: undefined"
6) Press [OK], settings/start page, choose "Albums"
7) kill app (double tap and swipe up)
8) Launch app
9) App is unusable with error "Error: TypeError: undefined is not an object (evaluating 't.getConnection().host') Script:
    file:///private/var/mobile/Containers/Bundle/Application/A7A7E5D0-CB75-49E0-B6DB-8B4278F5263E/MPD%20js.app/www/js/app-built.js Line: 240 Column: 25964 StackTrace: undefined"

**Comment by rbackhouse** [comment]
Fixed in Version 1.5

**Comment by asktoby** [comment]
Thank you!
