### ISSUE TITLE
question: Does it support switching audio outputs from the server.

### ISSUE THREAD

**Issue by divx118** [rbackhouse/mpdjs#8]
I couldn't find anywhere else to ask the question, but like the title says. I am in need of a mpd client for the iphone. It has however to support switching audio outputs from the server on and off, so I can choose in which room I play the music.

Thanks in advance.

**Comment by rbackhouse** [comment]
How are you managing the audio output separation? If via multiple MPD servers then you can simply add a connection configuration for each server/room. Selecting the connection will then select where the music is played.

**Comment by divx118** [comment]
I have a main mpd server which outputs http streams that are picked up by rpi which also runs a mpd server. those will then output to bluetooth audio. When a http stream is not available on the rpi I switch of the audio output and bluetooth. So on my main mpd server I have 3 http streams and a null output that is always on. The http streams are named "living room" "kitchen" "garden". Those I then can switch on and off to enable/disable audio in those named rooms.
I first wanted indeed multiple mpd servers, but not all clients support adding more then one server. Also I can now play the same audio in those rooms. 
I have now mpdluxe as client on the iphone of my wife, however it is a bit of a pain to add songs to the playlist. You have to add them one by one. On android I use mpdroid which just lets you add a album at once or an already created playlist at once.

Thanks anyway for taken the effort to respond. I assume you can't switch audio outputs with mpdjs. Maybe something for a future release...

**Comment by rbackhouse** [comment]
Ah ok I understand now. Currently MPDjs does not support switching output devices but I can look into adding it.

**Comment by divx118** [comment]
Would be nice thanks.

**Comment by rbackhouse** [comment]
FYI version 2.1, which was just released, includes support for enabling/disabling Outputs on the current connection

**Comment by divx118** [comment]
Nice thanks I will try it out. :)
